#!/bin/bash

clear

read -p "How old are you: " age

case $age in
[0-4])
	echo "Too young for school"
	;;

5)
	echo "Go to Kindergarden"
	;;

[6-9]|1[0-8])
	grade=$((age-5))
	echo "Go to Grade $grade"
	;;

*)
	echo "You are too old for school"
	;;
esac

