#!/bin/bash


fav_nums=(3.14 2.718 .57721 4.6692)

echo "Pi : ${fav_nums[0]}"

fav_nums[4]=1.1618

echo "GR : ${fav_nums[4]}"

fav_nums+=(1 7)

echo ""

for i in ${fav_nums[*]}; do
	echo $i
done

echo ""

for i in ${fav_nums[@]}; do
	echo $i
done

echo ""

echo "Array Length : ${#fav_nums[@]}"

echo ""

echo "Index 3 length: ${#fav_nums[3]}"

sorted_nums=($(for i in "${fav_nums[@]}"; do echo $i; done | sort)) 
echo ""

for i in ${sorted_nums[*]}; do
	echo $i
done

echo ""

unset 'sorted_nums[1]'
unset sorted_nums

