#!/bin/bash

str1=""
str2="Hi"
str3="Happy"

if [ !"$str1" ] 
then
	echo "str1 is NULL"
fi


if [ "$str2" == "$str3" ] 
then
	echo "$str2 equals $str3"
elif [ "$str2" != "$str3" ] 
then
	echo "$str2 is not equal to $str3"
fi


