#!/bin/bash

# Comment

echo "Hello World"

declare -r NUM1=5

num2=4

num3=$((NUM1+num2))
num4=$((NUM1-num2))
num5=$((NUM1*num2))
num6=$((NUM1/num2))

 
echo "5 + 4 =$num3"
echo "5 - 4 =$num4"
echo "5 * 4 =$num5"
echo "5 / 4 =$num6"

echo $((5**2))
echo $((5%4))

rand=5
let rand+=4
echo "$rand"


echo "rand++ = $(( rand++ ))"
echo "++rand = $(( ++rand ))"
echo "rand-- = $(( rand-- ))"
echo "--rand = $(( --rand ))"


cat<< END
Hi there, this function known as 
'cat' enables us to print in 
many lines. This is a very good
function for multiline comment 
END





